export const columnDefs = [
  {
    headerName: "PAN Card Number",
    field: "personalInfo.panCardNo",
    sortable: true,
    filter: true,
  },
  {
    headerName: "First Name",
    field: "personalInfo.firstName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Middle Name",
    field: "personalInfo.middleName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Last Name",
    field: "personalInfo.lastName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Father's First Name",
    field: "personalInfo.fatherFirstName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Father's Middle Name",
    field: "personalInfo.fatherMiddleName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Father's Last Name",
    field: "personalInfo.fatherLastName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Gender",
    field: "personalInfo.gender",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Marital Status",
    field: "personalInfo.maritalStatus",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Blood Group",
    field: "personalInfo.bloodGroup",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Date of Birth",
    field: "personalInfo.dob",
    sortable: true,
    filter: true,
    valueFormatter: (params) => 
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Date of Joining",
    field: "personalInfo.dateofJoining",
    sortable: true,
    filter: true,
    valueFormatter: (params) =>
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Permanent Address",
    field: "personalInfo.permanentAddress",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Phone Residence",
    field: "personalInfo.phoneResidence",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Personal Mobile Number",
    field: "personalInfo.personalMobileNumber",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Email ID",
    field: "personalInfo.pEmailID",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Dependent Persons",
    field: "dependentPersons",
    sortable: false,
    filter: false,
    cellRenderer: (params) =>
      params.value ? params.value.map((dp) => dp.name).join(", ") : "",
  },
  {
    headerName: "Personal References",
    field: "personalReferences",
    sortable: false,
    filter: false,
    cellRenderer: (params) =>
      params.value ? params.value.map((pr) => pr.name).join(", ") : "",
  },
  {
    headerName: "Professional References",
    field: "professionalReferences",
    sortable: false,
    filter: false,
    cellRenderer: (params) =>
      params.value ? params.value.map((pr) => pr.name).join(", ") : "",
  },
  {
    headerName: "Physical Disabilities",
    field: "additionalDetails.physicalDisabilities",
    sortable: true,
    filter: true,
    cellRenderer: (params) => (params.value ? "Yes" : "No"),
  },
  {
    headerName: "Marital Ineptness",
    field: "additionalDetails.maritalIneptness",
    sortable: true,
    filter: true,
    cellRenderer: (params) => (params.value ? "Yes" : "No"),
  },
  {
    headerName: "Court Proceedings",
    field: "additionalDetails.courtProc",
    sortable: true,
    filter: true,
    cellRenderer: (params) => (params.value ? "Yes" : "No"),
  },
  {
    headerName: "Employment - Date From",
    field: "additionalDetails.employmentDetails.datefrom",
    sortable: true,
    filter: true,
    valueFormatter: (params) => 
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Employment - Date To",
    field: "additionalDetails.employmentDetails.dateto",
    sortable: true,
    filter: true,
    valueFormatter: (params) => 
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Employment - Designation",
    field: "additionalDetails.employmentDetails.designation",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Employment - Last Salary",
    field: "additionalDetails.employmentDetails.lastSalary",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Interview - Date",
    field: "additionalDetails.interviewDetails.date",
    sortable: true,
    filter: true,
    valueFormatter: (params) => 
      params.value ? new Date(params.value).toLocaleDateString() : "",
  },
  {
    headerName: "Interview - Position",
    field: "additionalDetails.interviewDetails.position",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Interview - Location",
    field: "additionalDetails.interviewDetails.location",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Interview - Outcome",
    field: "additionalDetails.interviewDetails.outcome",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Languages",
    field: "additionalDetails.languages",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Two-Wheeler",
    field: "additionalDetails.twoWheeler",
    sortable: true,
    filter: true,
    cellRenderer: (params) => (params.value ? "Yes" : "No"),
  },
  {
    headerName: "Four-Wheeler",
    field: "additionalDetails.fourWheeler",
    sortable: true,
    filter: true,
    cellRenderer: (params) => (params.value ? "Yes" : "No"),
  },
  {
    headerName: "Driving License (Two-Wheeler)",
    field: "additionalDetails.drivingLicenseNoTwoWheeler",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Driving License (Four-Wheeler)",
    field: "additionalDetails.drivingLicenseNoFourWheeler",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Related Employee Name",
    field: "additionalDetails.relatedEmployeeName",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Professional Membership",
    field: "additionalDetails.memberOfAnyProfessional",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Specific Training Needed",
    field: "additionalDetails.needAnySpecificTraning",
    sortable: true,
    filter: true,
  },
  {
    headerName: "Additional Information",
    field: "additionalDetails.anyInformation",
    sortable: true,
    filter: true,
  },
];
